version: '3'

services:
  pipeline:
    image: s3-postgres-pipeline
    environment:
      - AWS_ACCESS_KEY_ID=add_your_access_key
      - AWS_SECRET_ACCESS_KEY=add_your_secret key
      - AWS_REGION=eu-north-1
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
