version: '3'

services:
  pipeline:
    image: s3-postgres-pipeline
    environment:
      - AWS_ACCESS_KEY_ID=AKIA3NA7AS43P3PZM2I2
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=eu-north-1
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs